name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * * # 8 am IST Every Day
    - cron: 00 14 * * * # 730 pm Every Day
    - cron: 00 06 * * 1-5 # 1130 am From Mon to Fri

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v5.0.0

      - name: Install Nodejs and npm
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '22'

      - name: Install newman and html-extra globally
        run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection with newman
        run: |
             newman run 'Inwarranty-flow Collection Copy.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testdata.csv \
             -r cli,htmlextra

      - name: Newman report
        if: always() # ensures that the archive executed irrespective whether the previous step has passed or not
        uses: actions/upload-artifact@v5.0.0
        with:
          name: Newman Report
          path: newman/*.html
